First commit for my Terraform project in Azure Devops

diff --git a/azure-pipeline.yaml b/azure-pipeline.yaml
--- a/azure-pipeline.yaml
+++ b/azure-pipeline.yaml
@@ -32,21 +32,27 @@ stages:
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
-                echo "Fetching Azure authentication details..."
-                # Get Subscription ID
+                echo "Logging into Azure..."
+                az account show
+                if [ $? -ne 0 ]; then
+                  echo "Azure login required. Attempting login..."
+                  az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                fi
+
+                # Set Subscription Context
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+
+                # Get Authentication Details
                 export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-                echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" >> $GITHUB_ENV
-
-                # Get Tenant ID
                 export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
-                echo "ARM_TENANT_ID=$ARM_TENANT_ID" >> $GITHUB_ENV
-
-                # Get Client ID from service principal
                 export ARM_CLIENT_ID=$(az ad sp list --display-name $(AZURE_SUBSCRIPTION) --query "[0].appId" -o tsv)
-                echo "ARM_CLIENT_ID=$ARM_CLIENT_ID" >> $GITHUB_ENV
+
+                # Debug output
+                echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID"
+                echo "ARM_TENANT_ID=$ARM_TENANT_ID"
+                echo "ARM_CLIENT_ID=$ARM_CLIENT_ID"
 
                 # Set Terraform environment variables
-                echo "Setting Terraform authentication environment variables..."
                 echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$ARM_SUBSCRIPTION_ID"
                 echo "##vso[task.setvariable variable=ARM_TENANT_ID]$ARM_TENANT_ID"
                 echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$ARM_CLIENT_ID"
