First commit on my terraform project using AZ Devops Pipeline.

diff --git a/azure-pipeline.yaml b/azure-pipeline.yaml
--- a/azure-pipeline.yaml
+++ b/azure-pipeline.yaml
@@ -32,8 +32,10 @@ stages:
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
-                az account show --output json || echo "Azure authentication failed."
-                echo "Authentication setup complete."
+                echo "Logging into Azure..."
+                az account show --output json || (echo "Azure authentication failed." && exit 1)
+                echo "Azure authentication successful."
+
 
           # Step 3: Set Environment Variables for Terraform Authentication
           - script: |
